spring:
  application:
    name: yu-picture-backend
  datasource:
    url: jdbc:mysql://localhost:3306/yu_picture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  profiles:
    active: local
  # 文件上传的最大体积
  servlet:
    multipart:
      max-file-size: 10MB
server:
  servlet:
    context-path: /api
  port: 8080

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.subaiqiao.yupicturebackend.controller
