spring:
  application:
    name: yu-picture-backend
  datasource:
    url: jdbc:mysql://localhost:3306/yu_picture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #Redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  profiles:
    active: local
  #Session
  session:
    store-type: redis
    # Session 30天后过期 60 * 60 * 24 * 30
    timeout: 2592000
  # 文件上传的最大体积
  servlet:
    multipart:
      max-file-size: 10MB
  # 空间图片分表
  shardingsphere:
    datasource:
      names: yu_picture
      yu_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yu_picture?allowPublicKeyRetrieval=true
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yu_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.subaiqiao.yupicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

server:
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000 # Session 30天后过期
  port: 8080

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
    enable-sql-runner: true

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.subaiqiao.yupicturebackend.controller
